apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: foundation
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: broadinstitute/foundation
spec:
  type: website
  owner: dsp-devops@broadinstitute.org
  lifecycle: experimental
