apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: terra
  description: |
    Terra is a cloud-native platform for biomedical researchers to access data, run analysis tools, and collaborate.
  tags:
    - dsp
    - terra
    - java
spec:
  owner: broadwrite
